### ISSUE TITLE
firefox content block drag issue

### ISSUE THREAD

**Issue by nickburne** [pootlepress/pootle-page-builder#35]
When you drag a content block to a different cell in firefox, the content block positition is way out when dragging it.

**Comment by shramee** [comment]
Hey Duncan,
Kindly test this and help me understand the issue...

**Comment by DuncanChittick** [comment]
I've recorded a video and added to slack for your reference: 

http://duncandemo.thisistap.com/wp-content/uploads/2015/07/ScreenFlow.mp4

**Comment by shramee** [comment]
Yo Nick,

This might require the modifications to the jq ui sortable widget.
Since it is a part of wp core, including ours modified version would drive us slightly away from core, which is why we need you to help us decide what should be done for this...

Moreover I can't reproduce the bug to the magnitude you guys get it... Only a couple of pixels ( about 10 +-5 ) but you guys are getting it off about 75 +-25 px which looks horrible ( Thanks to Duncan's video ).

Lemme know.

Cheers

**Comment by nickburne** [comment]
Happens when title is used to drag - please fix!

**Comment by nickburne** [comment]
Put code on a separate branch. I have moved this to 0.3.0

**Comment by shramee** [comment]
Lemme kno0w how it works for ya,
Branch ppbDialog ;)

**Comment by nickburne** [comment]
Looks like this is done well, so please merge into master branch.

**Comment by shramee** [comment]
Done

**Comment by nickburne** [comment]
Nice.
