### ISSUE TITLE
White screen on de-activation

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#359]
![screen shot 2016-08-18 at 12 36 01](https://cloud.githubusercontent.com/assets/3070779/17772395/71fd02d8-6540-11e6-9066-eaba3a661e06.png)

**Comment by shramee** [comment]
This is probably because of us trying to populate ppb content (after processing) in posts/pages...

![image](https://cloud.githubusercontent.com/assets/11048263/17776438/2ed30388-657a-11e6-974a-245cbf94fb86.png)

Over 200mb of RAM got used in this process because of so many pages/posts on pb.uk

We don't need this anymore so let's remove ( coz we do it when we save the page 😉  )
