### ISSUE TITLE
Live Template Branch - Mobile column stacking not working properly if multiple columns and keep custom padding is used

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-page-builder#626]
See this page as an example 

See 2nd row. 

http://www.storefront-pro.com/ksdf/

**Comment by shramee** [comment]
Hi,

IIRC, this is a limitation... we have set the styles to work only when the column is both first and last child i.e. it's the only child...

It would be a huge update, but I think we should move to using flex boxes since now over 97% of browsers support it :)
http://caniuse.com/#feat=flexbox

Also, Divi has used those right from the beginning, So would be really nice coz it has fancy features like vertical alignment, stretching cells height etc baked right into it :)
